/**
 * @File Name          : TaskTrackerConstants.cls
 * @Description        :
 * @Author             : Revolution Group (Brian Ezell)
 * @Group              :
 * @Last Modified By   : Revolution Group (Brian Ezell)
 * @Last Modified On   : 5/11/2020, 9:33:20 PM
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    5/11/2020   Revolution Group (Brian Ezell)     Initial Version
**/
public class TaskTrackerConstants {
    public static final String TASK_PENDING_STATUS = 'Waiting On Other Tasks';
    public static final String TASK_START_STATUS = 'Not Started';
    public static final String TASK_COMPLETED_STATUS = 'Completed';
}